# Generated by Django 2.2.14 on 2020-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
