# Generated by Django 3.1.4 on 2020-12-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
