# Generated by Django 3.0.4 on 2021-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0004_auto_20210210_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(choices=[('biryani', 'biryani'), ('cooldrinks', 'cooldrinks'), ('manchuria', 'manchuria'), ('noodles', 'noodles'), ('fried', 'fried')], max_length=200),
        ),
    ]
