# Generated by Django 3.0.4 on 2021-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0005_auto_20210210_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('name', models.ManyToManyField(blank=True, null=True, to='QR.Item')),
            ],
        ),
    ]
