# Generated by Django 3.0.4 on 2021-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='item',
        ),
    ]
