# Generated by Django 3.0.4 on 2021-02-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0007_auto_20210210_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='QR.Item'),
        ),
    ]
