# Generated by Django 3.0.4 on 2021-02-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR', '0009_auto_20210211_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='rate',
            new_name='line_total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
